[env]
# Common environment defaults can be placed here if shared

[[services]]
name = "ads2go-server"
root = "Ads2Go-Server"
start = "npm start"
build = "echo 'no build step'"
# Expose default port via PORT env (handled by app)

[[services.env]]
# Set your actual values in Railway after first deploy
PORT = "5000"

[[services]]
name = "ads2go-client"
root = "Ads2Go-Client"
build = "npm ci && npm run build:ci"
start = "npx --yes serve -s build -l $PORT"

[[services.env]]
# REACT_APP_GRAPHQL_URI should be set after the server deploys
# Example placeholder; update in Railway dashboard to real server URL
REACT_APP_GRAPHQL_URI = "https://your-server.onrender-or-railway.app/graphql"
PORT = "3000"


