[env]
# Common environment defaults can be placed here if shared

[[services]]
name = "ads2go-server"
root = "Ads2Go-Server"
start = "npm start"
build = "echo 'no build step'"
# Expose default port via PORT env (handled by app)

[[services.env]]
# Set your actual values in Railway after first deploy
PORT = "5000"

[[services]]
name = "ads2go-client"
root = "Ads2Go-Client"
build = "npm ci && npm run build"
start = "npx --yes serve -s build -l $PORT"

[[services.env]]
# Client will use the server's Railway URL - update this after server deploys
REACT_APP_API_URL = "https://ads2go-integration-production.up.railway.app/graphql"
PORT = "3000"


