[build]
builder = "NIXPACKS"
buildCommand = "echo 'no build step'"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT = "5000"
NODE_ENV = "production"
