[build]
builder = "NIXPACKS"
<<<<<<< HEAD
=======
buildCommand = "echo 'no build step'"
>>>>>>> jairhon_cleanup-directory

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
<<<<<<< HEAD
NODE_ENV = "production"
=======
PORT = "5000"
NODE_ENV = "production"
>>>>>>> jairhon_cleanup-directory
