services:
  - type: web
    name: ads2go-server
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: CLIENT_URL
        value: https://ads2go-client-dxo4.onrender.com
    disk:
      name: server-disk
      mountPath: /data
      sizeGB: 1
