[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_OPTIONS = "--max-old-space-size=4096"
GENERATE_SOURCEMAP = "false"
INLINE_RUNTIME_CHUNK = "false"
NODE_ENV = "production"
REACT_APP_API_URL = "https://ads2go-integration-production.up.railway.app"
REACT_APP_GRAPHQL_URL = "https://ads2go-integration-production.up.railway.app/graphql"
REACT_APP_SERVER_URL = "https://ads2go-integration-production.up.railway.app"
REACT_APP_CLIENT_URL = "https://ads2go-client-production.up.railway.app"
