[build]
builder = "NIXPACKS"
buildCommand = "npm ci --omit=dev --no-audit --fund=false && npm run build"

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_OPTIONS = "--max-old-space-size=768"
NODE_ENV = "production"
GENERATE_SOURCEMAP = "false"
INLINE_RUNTIME_CHUNK = "false"
DISABLE_ESLINT_PLUGIN = "true"
NPM_CONFIG_AUDIT = "false"
NPM_CONFIG_FUND = "false"
